[package]
name = "create-secret"
version = "0.1.0"
edition = "2024"

[dependencies]
k8s-openapi = { version = "0.24.0", features = ["latest"] }
kube = "0.99.0"
tokio = { version = "1.44.2", features = ["macros", "test-util", "tokio-macros"] }
