apiVersion: batch/v1
kind: Job
metadata:
  name: create-secret
spec:
  template:
    spec:
      containers:
        - name: create-secret
          image: create-secret:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
