apiVersion: batch/v1
kind: Job
metadata:
  name: create-secret
spec:
  template:
    spec:
      containers:
        - name: create-secret
          image: {{ include "create-secret.image" . }}
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
      serviceAccountName: create-secret
