apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-secret
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-secret
subjects:
- kind: ServiceAccount
  name: create-secret
roleRef:
  kind: Role
  name: create-secret
  apiGroup: rbac.authorization.k8s.io