apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "idempotent-secrets.fullname" . }}
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: idempotent-secrets
          image: {{ include "idempotent-secrets.image" . }}
          imagePullPolicy: IfNotPresent
          args:
            - "idempotent-secrets"
            - --namespace
            - {{ .Release.Namespace }}
            - {{ .Values.secret.name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Never
      serviceAccountName: {{ include "idempotent-secrets.fullname" . }}
