name: Helm Chart Pipeline

on:
  push:
    branches: [main]
    paths:
      - CHANGELOG.md
      - helm/**
      - .github/workflows/chart.yml
  pull_request:
    branches: [main]
    paths:
      - CHANGELOG.md
      - helm/**
      - .github/workflows/chart.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  integration-test-reusable:
    uses: jneuff/create-secret/.github/workflows/integration_test_reusable.yaml@main

  release-please:
    runs-on: ubuntu-latest
    if: >
      github.event_name != 'pull_request' || 
      !startsWith(github.event.pull_request.title, 'chore(main): release')
    needs: ["integration-test-reusable"]
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT_ACTIONS }}
      - run: echo 'release-please result> ${{ toJSON(steps.release-please) }}'
      - if: ${{ steps.release-please.outputs.release_created }}
        run: echo ${{ steps.release-please.outputs.tag_name }}
      - if: ${{ needs.integration-test-reusable.result }} == 'success'
        run: echo "integration tests pass"

  publish-chart:
    runs-on: ubuntu-latest
    needs: ["integration-test-reusable", "release-please"]
    steps:
      - run: |
          echo "Debug"
          echo "${{ toJson(needs.release-please.outputs) }}"
      - if: ${{ needs.release-please.outputs.release_created }} && ${{ needs.integration-test-reusable.result }} == 'success'
        run: |
          echo ${{ needs.release-please.outputs.tag_name }}
          echo "create helm release"
