name: Required Failsafe

on:
  pull_request:
    branches: [main]
    paths:
      - README.md
      - CHANGELOG.md
      - release-please-config.json
      - .release-please-manifest.json

jobs:
  required-reusable:
    uses: ./.github/workflows/required_reusable.yaml